# Generated by Django 3.1.2 on 2020-10-10 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_auto_20201009_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='user',
            new_name='fuser',
        ),
    ]
