version: "3.8"
services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/sdata/
    env_file:
      - ./app/.env
  foodgram:
    build: .
    expose:
      - 8010
    depends_on:
      - db
    env_file:
      - ./app/.env
    volumes:
      - ./app:/code
  nginx:
    restart: always
    build: ./nginx    
    ports:
      - 8010:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d  
      - ./app:/code
    depends_on:
      - foodgram

volumes:
  postgres_data:  