# Generated by Django 3.1.2 on 2020-10-08 00:08

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20201007_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(upload_to=recipes.models.user_directory_path, verbose_name='Картинка'),
        ),
    ]
