# Generated by Django 3.1.2 on 2020-10-09 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20201008_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipes',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_count', to='recipes.recipes', verbose_name='Рецепт'),
        ),
    ]
