# Generated by Django 3.1.2 on 2020-10-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20201009_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipes',
            name='count',
            field=models.IntegerField(verbose_name='Количество'),
        ),
    ]
