# Generated by Django 3.1.2 on 2020-10-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vk',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Адрес страницы VK'),
        ),
    ]
